site_name: MkDocs Demo
site_url: https://dhufe.github.io/mkdocs-demo/
repo_url: https://github.com/dhufe/mkdocs-demo
theme:
  name: material
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  features:
#    - navigation.tabs
#    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.suggest
    - search-highlight
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
  language: de
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: "Wechsel in den Darkmode"
      #accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: "Wechsel in den Lightmode"
plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - admonition
  - footnotes
  - attr_list

nav:
  - Home: index.md